PACKAGE_NAME="t2bce_vhci"
PACKAGE_VERSION="0.02"

MAKE[0]="make KVERSION=${kernelver} T2BCE_CORE_SRC=t2bce_core"

BUILT_MODULE_NAME[0]="t2bce_vhci"
DEST_MODULE_LOCATION[0]="/updates/dkms"

AUTOINSTALL="yes"
