---
name: Update t2bce

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout Repo'
        uses: actions/checkout@v7
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Sync upstream commits with history
        id: publish
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          chmod +x scripts/sync-from-kait2en.sh
          ./scripts/sync-from-kait2en.sh

      - name: Push changes to the repo
        if: steps.publish.outputs.synced == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Push changes to the patches
        if: steps.publish.outputs.synced == 'true'
        run: |
          git clone https://github.com/pierolenzo/linux-t2-patches.git
          cd linux-t2-patches
          gh workflow run bce.yml -f fork="https://github.com/${{ github.repository }}" -f branch="${{ github.ref_name }}"
        env:
          GH_TOKEN: ${{ secrets.PAT }}
